name: Package and Release Extension

on:
  push:
    branches:
      - main

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get current date
        id: date
        run: echo "DATE=$(date +'%Y-%m-%d-%H-%M')" >> $GITHUB_ENV

      - name: Create ZIP file
        run: |
          zip -r "firxa-${{ env.DATE }}.zip" . -x "*.git*" "*.github*"

      - name: Delete previous pre-release
        uses: dev-drprasad/delete-tag-and-release@v0.2.1
        with:
          delete_release: true
          tag_name: pre-release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        continue-on-error: true

      - name: Create new pre-release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: pre-release
          release_name: Fejlesztői build
          body: |
            A build automatikusan készült ${{ env.DATE }}-án/én.
            Ez egy kiadás előtti build, amely minden egyes commit után frissül.
          draft: false
          prerelease: true



      - name: Upload ZIP to release
        if: steps.create_release.outputs.upload_url != ''
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./firxa-${{ env.DATE }}.zip
          asset_name: firxa-${{ env.DATE }}.zip
          asset_content_type: application/zip
